# Generated by Django 4.1.7 on 2023-03-09 09:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bbq', 'BBQ'), ('garden', 'Garden'), ('gym', 'Gym'), ('lounge', 'Lounge'), ('parking', 'Parking'), ('spa', 'Spa'), ('wifi', 'Wi-Fi')], max_length=200, null=True),
        ),
    ]
