# Generated by Django 4.1.7 on 2023-03-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_property_image', upload_to='property_thumbnails'),
        ),
    ]
